tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:fvtMQbk3Dp84PKMb4KYobt4nhqo9vIcPtpBlhiumJcWJW9bXSrW9SyJcFPv/6dx4Ommr,iv:08DecTX0gVcSeugyRW88HNzzJ5KXocFt4Wo12XnjbPA=,tag:3ycr/HwxDv0AtzIGj6KGoA==,type:str]
                username: ENC[AES256_GCM,data:648YxrE=,iv:OXJmEAwdAIHHYm7X5hH7iVrTCJFD7EQNm0v7chk3V48=,tag:PkzHay3l+o1PLwsG6CAcWg==,type:str]
                password: ENC[AES256_GCM,data:V3o4V6fQf0741Jk=,iv:6NyiQeSa/mBCZ7/2rKFJTdxRzWGo7crhxUc/dd+8AuU=,tag:kA1HdTfcs/adrHG0Byt7cg==,type:str]
        tap_gui:
            app_config:
                auth:
                    allowGuestAccess: ENC[AES256_GCM,data:3m63vQ==,iv:l0v44GZUathe8BaSPGTzXW8+niEvCLWlaAkgxzBNVA4=,tag:Nt5874AM/Yk0g9g5Yrfq+Q==,type:bool]
                    environment: ENC[AES256_GCM,data:GLBwI/CcYa2ttfM=,iv:9/cRSErNZb83QYquQChsvJFjDAm3d2TlV/FZhp40Hf0=,tag:hhtCBkO74Z0uMiwhRDlNUQ==,type:str]
                    providers:
                        github:
                            development:
                                clientId: ENC[AES256_GCM,data:+sfCnbZgzZm6bjKdZRc/4pNkhZg=,iv:gwzfHXaCCWZN+jqeIMNoLNn0GzQWmDkCSQHZFs5KL0M=,tag:+B0RK/trSAyMVyCeDyKlxA==,type:str]
                                clientSecret: ENC[AES256_GCM,data:9QIZu5mr1Ggpw+IGf2UHXD+/ByOUajhi3rO7nw0wR9nhOsaYzhPSwQ==,iv:n1gMqeYa8uT1+g3b1fieIdMvzqHhl8AD/0IlYj7G9fU=,tag:w+OcQ6VOsneK1jZXs2vhBw==,type:str]
                integrations:
                    github:
                        - host: ENC[AES256_GCM,data:JBj7pGGP2w1Gpg==,iv:otakTJtJ4k7FC5Jx1isdLZ9DwRVyrgWiRIKstdSkACw=,tag:OZb1L/EtxP34UIU+kbwWyA==,type:str]
                          token: ENC[AES256_GCM,data:j3QYVBfFzvnbpGnrRQxWdw6lgiyfF8PC+Tfd+rvwRdatXHZlQKNIlQ==,iv:y4ICn8zsHD0xjILyOSBG4jLdhB3wPAIDgp82ykx14SQ=,tag:Xc7fsGTZVi5qSQvnc1HFcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snr2tw7r5guqqdy2frcfd3wv4gu7eq6vnuvgcaa8kx0qlf5f2efqfc95v6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd3daYm5lakpva01BZ0hQ
            bk9ibGx6UHpkYzI1ZGVRcGRBTzdkSDZVVUZFCkg1aWo4b0dZNDRRNGhTL0I4bWhm
            aUlCK29KeWdVd2NnTG96TFVhZ05xUTgKLS0tIHRFa2t3dmlBelJHd1V3ZncvMzNw
            KzZxejdkRGVOVTZ6eU5TZjcwMVA5OG8KsjpXz11ML3DOjyE1Qe3gpjz6B2Gkd2TM
            lPPOcfvWE4gh9E4mlmvvb2EF+O+/2wqKcmbkTbDgOMz0Q5lEA3l5LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T09:17:47Z"
    mac: ENC[AES256_GCM,data:6XXQhcxvkEHF+TVtFUO0pLJ4vlZ94JUonqNypAqz6MbtNrxen/OGpjJY/YV/DZU7jmmeFZwHmHPRWYe9SILR/Zk4PhhNkA3CtV5Sir858k3BnSZ9U6nE2s7iYLQPr7ccpZDvr57A0W5IMrs5LhcnTGORDNsnXvUuOLhuKphx7FQ=,iv:3PpBnbL87gQtCeAKvejo9Li9vrLk3D/f9gTneMkuL2s=,tag:9LTm/MzBamZ2L6SOSTSzRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
