apiVersion: ENC[AES256_GCM,data:qj8=,iv:nNQwdoKxg0FVlUqCYslIUhTIVJ2AdO6UEG8wY3vxfl8=,tag:4VJ/AYZGnkIktXiB8k46bw==,type:str]
kind: ENC[AES256_GCM,data:QAkgl4Q7,iv:IOD1LQsQ/ZPfWSjXLVxNFi0syIsA3bElCrtWvxV66IY=,tag:+fHnN7buBK978GXpbguD7Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:veJMPbCdtmXN0IGJ47o=,iv:cCGkcaFwo8RqBItU24ru2svzkr/CX/3VwllWL4C1GNE=,tag:ohDNDjatmAb9FWRthhbtUQ==,type:str]
    namespace: ENC[AES256_GCM,data:P6E+aEbotH0pL+E=,iv:NeBg4csO75Az0H6fDgS7NWArlZSkhCSG/8hCb4F8qV0=,tag:KFbYiTLfHF17lmReKdeHTw==,type:str]
type: ENC[AES256_GCM,data:7oaCzleKozVwtQ6Eiggu+iIdlWV9q/juUm/oZLwB,iv:/NxjHfhj0RRrCkxx5Lkoi6mSSkxlHdDQO/wWxrTrzBo=,tag:B5+Q+XQtyyUpVv4MC2DMzw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Ykw/7RL6ZmdXqKTFBmqrBFmhAtZb42lx+0ZHwTVjZDzYk3agmxdAT8VrhN3YwWJAZHSfKqVxI98XdcY9rZ7CEbuEOTUXtD8d9sOx+waRDUwpBfNBQI9lvQcdcGz1qnMCkLmRDMeYqR2ahrg3Boi+0ItZ0AFopsm/KnCB7MbAQTx7A2C2lc6l5/fGo55FDQWQ/ECIBh4CWU3TG7AEU6ajqY1fpJAWise079XjrWJoWRvv+zmsAwa5sR/F5Fk1tIBnm2ICU4o7XkQj4bE9NeqW1iafwbT4p4zShyoZ3DuSozU=,iv:erdMs2uyk1h+yErIiKNUBR3aog318NU4PwoAzmel3Mw=,tag:pP0XsvVClVEpYmcWgNwj1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snr2tw7r5guqqdy2frcfd3wv4gu7eq6vnuvgcaa8kx0qlf5f2efqfc95v6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSW4rU1hwK2ZNWms5NSsv
            Mm44T2JpNTNuVm1NRWs3U3BVdTBwNERBalZVCkQxSytEbk1uQnhON2QwK0k0V1F6
            ellHeEtWL3YzVXNIYStHOUJuelM4amMKLS0tIFVxUUVxTTVOQjdHVjlNTWtvckJF
            TURvNFVRckdqbFhNbThhZmtpTS9Ta2cKYkfkBGaKwDaKnAaFfLaknbztFR01CkgC
            MQHK/iwOQt1pnM1zfGY6QPTI44fWVqiCbHOHWYW9cUTQVUPwPY9O4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T09:17:47Z"
    mac: ENC[AES256_GCM,data:9bazR7PSlPCMtTdF3LcneYF/IG5xRch/S19LOKknE8GnWLcaBSIoerMzvtohh+lDh5c3sFqhxpOiDo+XdsPSO4IjodHLQDNOetBIo04xlENE5O36FZV+l8VgmGppwUQdxgEnKOuu94HTf3DytXC96DAlFdI7+CZo0hR9UyXnxvs=,iv:SsgpyCl40ObwDPdyQBhAIl3t4gxU/J7byLXtYVQB2gU=,tag:A2+E4/F6xXJHi3GkrAnl/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
