apiVersion: ENC[AES256_GCM,data:zho=,iv:qef9axgYHueDcwibC+coLn7cNg3CXFq9TxGKJy6pShw=,tag:/DtnzspR2MIGJjfK7qSP8Q==,type:str]
kind: ENC[AES256_GCM,data:+9ugHKF3,iv:dWraj1avzwr9qLja8LQhk5C2vW+fnAYsnywzzmnkMA8=,tag:GC+Qbyj3+LK8mMC7NQfo/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rqiIaKuxVrO4PiZnO1Q=,iv:DLak4Y9mXJW+g83Z8g4pzSHQuUPVgo3bJTLOY5ymlIk=,tag:KftRvjrt+9vrH/HMCC+j2g==,type:str]
    namespace: ENC[AES256_GCM,data:bbNlc8kBCb+ZnVM=,iv:cJxVQ1u7rY9+PROqakNEbMQTBuGxCNPg94aZj+cf9Sk=,tag:GQoihbvl9jTVMdS2Vw2cog==,type:str]
type: ENC[AES256_GCM,data:jg0bUBo+sWMwMmLm5jzzYuxgK3Z8/rrqnc4hNlul,iv:KFRYE9SVlWTh3hQIMGePc/4+UHXVYzMzFPLoMNlpm30=,tag:7THmWGbFQ8frehP6JLP7+g==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:tcphRLwK5bj39eXf5s7dfRFMcPbESBCPUfn7NHkhv0WmkvtJMxOMPMNYvLOnWPYjolQC1WxX8/fbUatj0OWmBbeN8W+D3wI5QGyk0PCIBtB1x5A4o+AXtKif1iqDsollmioj+vvJllI6pgNo/dP5FNPgyLEOBrtxT0nbxm4MfTLhBHcz/b4WIYdpv8StGPF7mLECaG0dejwrqiGa3pHJp6sl+rq8OZdyJ8mEfNIutjNp4XWepiakjQ==,iv:YaSq5IFiGvAmdTY8RbKe9R2M+MBWy0imYeOPi5SMp28=,tag:oCUWH2Vq9C9rHkOFGFAjDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w457zlmq74y9wy8gepfu4rzlxuhyq3xvr8803tu4ahasmqvhpd2q2s3f5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMDg0cDVlQzBhTGJUQkZJ
            d0FDMWpDRDNaTlMvQlpnYXY3aEtXdDZQdVNFCjZacUFEK1gxaFNwbzVUTmJkaWFu
            YlB6OWQ1WFgwY0NYYzdnYTcyMkFVeXcKLS0tIHhOKy9qTDNsRVdOL2Y3aEh4OXhq
            NFdYeG9pRjluLzFCU1JEanZ2d2R3dEkK2c8e8bIHVNDyatyRBE3caalNAT7pjfSc
            IeJaNjd0PCB3VVeazDFsfecm2okOuTlf+D/74d8NbPm/yDeTMRq3zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T12:55:59Z"
    mac: ENC[AES256_GCM,data:fO0Tmmqr8MMEh5AAwEYCgTaSLIHxFQ/oFJmPuRG6dQwnSBbw9iJjfwL2f7OMUXD1Kv2XsH9hKWSywFKme93zx8XIkVDJAx7asbMWObJC7kofaM8fZW2zZ32GL6uY6+MNUOAcjFlJwZ+rUNKN1N1HHKJelNvqA7ih1ByRoLdiwJk=,iv:TXiAFsS3qgIsEiDaByDTglPHd0FxmvTDiIRNJEjvylI=,tag:ugx1i4b++//qMOVnNInIOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
