apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: rmq
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: rmq-repo
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/p-rabbitmq-for-kubernetes/tanzu-rabbitmq-package-repo:1.5.1
