apiVersion: ENC[AES256_GCM,data:zic=,iv:FsHeZpdI8h0NHD72jyMvhHufIFDF0hXhn2yXgT4G2UA=,tag:gtrY3IC8UC345VRhU1XcHA==,type:str]
kind: ENC[AES256_GCM,data:wCDzmGX8,iv:OnsFOK17gbR//G8uG4R9NtXP+gTQ58eKd3mdOdfkkW8=,tag:D2ZjGdmlwV0XNbcZBCKpgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RAjLLJNpfTIH8K6u1p52,iv:zMpj8PlPU/rOtuyDSJyGpXEYl4rFD89Gns2axxRnyvw=,tag:r7ffmsAEMmSA3sRi4MAAXw==,type:str]
    namespace: ENC[AES256_GCM,data:SerFZpvjDpWs9Q==,iv:gMSZE+8ft5wKIR+qcUnX5/Noo+JeMXCBZSnfk2r6r1A=,tag:m+xtC/mBJO/AOa95VzTfUw==,type:str]
type: ENC[AES256_GCM,data:vogvRpv3,iv:Cs22xV+iK8wpXA6L7+91yxQjujhmH46n/ixSsiXaw50=,tag:N3O1wb78ly6/gANJYPhOWw==,type:str]
data: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snr2tw7r5guqqdy2frcfd3wv4gu7eq6vnuvgcaa8kx0qlf5f2efqfc95v6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOURrRUpXNlFjRTJsbkxy
            WlIzMHpXckMyU20xYjVQa090TUdReFlRWWk0ClE0Smw3OS8zWmFvYlFKUjF0eE4x
            YjNlMHVMR2xKQVhxeXJKbUVqQU9qMFkKLS0tIGZhVlU1VFlFYXZBOVZXbzVrNGRv
            VnV0RzFnM3hYM3BKUklCZmJLT3ZoNG8KubTMXUS+HUOz08yCpI6Ho9xHE801jDf2
            g2rUfPLcDLl/EhCqB8mB3NndmqpRGda66U8BSBR5aNxbnMnr7EhE7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T09:17:47Z"
    mac: ENC[AES256_GCM,data:LGieq/hvYrq+CdeFUyzYrgaUFyq0faYw2mikl2pjkKU1AIEt6F48LbnObmaD7xpdhaMV3d6k2r9OSgwjYQYUujsiS0qEkB1I+rXeXlNytzc+IweglEwi8Kn9tyzC1t7rmv26OGbhEe4Q+LOiVmkSaR6ofoxB9Ogd7A1PYB6uA60=,iv:ClFWoExvfirhAOAL3WVLhtBJuTbiqyyvR3EtHvELpCU=,tag:+EMaE96igaNoydN3aaXM3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
