apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-portal-tls-cert.yaml
  namespace: api-portal
spec:
  dnsNames:
  - api-portal.aks-itn-1.where4dinner.com
  secretName: api-portal-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
